version: '3'

services:
  mongodb:
    build: .  
    ports:
      - "27017:27017"  
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: perguntechdb
    volumes:
      - mongodata:/data/db  

volumes:
  mongodata:   
